version: '3'

services:
  proxy:
    image: nginx:1.11 # this will use the latest version of 1.11.x
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
    volumes: #its a linking, so default.conf will be replaced by nginx.conf
    #ro means read only means can not be changed from within the container
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  web:
    image: httpd  # this will use httpd:latest
