version: '3' #version has to be string

services:
  jekyll: #here name is the --name property. which will be DNS name
    image: bretfisher/jekyll-serve # this is the image name
    volumes: #volume is list that why plural
      - .:/site #does not need pwd. here dot means current directory and linked to /site inside container
    ports: #port is also list thats why plural.
      - '80:4000' #ports are given as string input thats why single quote
